# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\info.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 800)
        Form.setMinimumSize(QtCore.QSize(1200, 800))
        Form.setMaximumSize(QtCore.QSize(1200, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\icon/detail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QWidget {\n"
"    background-color: #ffffff; /* Set background color */ \n"
"    border-radius: 20px;  /*Set corner radius*/\n"
"}")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 600, 450))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame#frame { \n"
"border-radius: 5px; /* Set rounded corners */ \n"
"background-color: #ecedee; /* Set background color */ \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_41 = QtWidgets.QFrame(self.frame)
        self.frame_41.setGeometry(QtCore.QRect(5, 5, 590, 440))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.frame_41.setFont(font)
        self.frame_41.setStyleSheet("/* QLabel Default style */\n"
"QLabel {\n"
"    color:  #000000; /* Text color */\n"
"    font-size: 16px; /* Font size */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"QFrame#frame_41 {\n"
"    background-color: #ffffff; /* Set background color */ \n"
"    border-radius: 5px;\n"
"}")
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.label_138 = QtWidgets.QLabel(self.frame_41)
        self.label_138.setGeometry(QtCore.QRect(10, 5, 271, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_138.sizePolicy().hasHeightForWidth())
        self.label_138.setSizePolicy(sizePolicy)
        self.label_138.setMinimumSize(QtCore.QSize(0, 0))
        self.label_138.setMaximumSize(QtCore.QSize(2200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_138.setFont(font)
        self.label_138.setStyleSheet("/* QLabel Default style */\n"
"QLabel#label_138 {\n"
"    color: #000000; /* Text color */\n"
"    font-size: 24px; /* Font size */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}")
        self.label_138.setObjectName("label_138")
        self.r1 = QtWidgets.QPlainTextEdit(self.frame_41)
        self.r1.setGeometry(QtCore.QRect(10, 37, 570, 97))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.r1.setFont(font)
        self.r1.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.r1.setReadOnly(True)
        self.r1.setOverwriteMode(False)
        self.r1.setObjectName("r1")
        self.r2 = QtWidgets.QPlainTextEdit(self.frame_41)
        self.r2.setGeometry(QtCore.QRect(10, 137, 570, 97))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.r2.setFont(font)
        self.r2.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.r2.setReadOnly(True)
        self.r2.setOverwriteMode(False)
        self.r2.setObjectName("r2")
        self.r3 = QtWidgets.QPlainTextEdit(self.frame_41)
        self.r3.setGeometry(QtCore.QRect(10, 237, 570, 97))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.r3.setFont(font)
        self.r3.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.r3.setReadOnly(True)
        self.r3.setOverwriteMode(False)
        self.r3.setObjectName("r3")
        self.r4 = QtWidgets.QPlainTextEdit(self.frame_41)
        self.r4.setGeometry(QtCore.QRect(10, 337, 570, 98))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.r4.setFont(font)
        self.r4.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.r4.setReadOnly(True)
        self.r4.setOverwriteMode(False)
        self.r4.setObjectName("r4")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 455, 600, 345))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("QFrame#frame_2 { \n"
"border-radius: 5px; /* Set rounded corners */ \n"
"background-color: #ecedee; /* Set background color */ \n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_47 = QtWidgets.QFrame(self.frame_2)
        self.frame_47.setGeometry(QtCore.QRect(5, 5, 590, 335))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.frame_47.setFont(font)
        self.frame_47.setStyleSheet("/* QLabel Default style */\n"
"QLabel {\n"
"    color:  #000000; /* Text color */\n"
"    font-size: 16px; /* Font size */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"QFrame#frame_47 {\n"
"    background-color: #ffffff; /* Set background color */ \n"
"    border-radius: 5px;\n"
"}")
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.label_141 = QtWidgets.QLabel(self.frame_47)
        self.label_141.setGeometry(QtCore.QRect(10, 5, 201, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_141.sizePolicy().hasHeightForWidth())
        self.label_141.setSizePolicy(sizePolicy)
        self.label_141.setMinimumSize(QtCore.QSize(0, 0))
        self.label_141.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_141.setFont(font)
        self.label_141.setStyleSheet("/* QLabel Default style */\n"
"QLabel#label_141 {\n"
"    color: #000000; /* Text color */\n"
"    font-size: 24px; /* Font size */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}")
        self.label_141.setObjectName("label_141")
        self.l1 = QtWidgets.QPlainTextEdit(self.frame_47)
        self.l1.setGeometry(QtCore.QRect(10, 37, 570, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.l1.setFont(font)
        self.l1.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.l1.setReadOnly(True)
        self.l1.setOverwriteMode(False)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QPlainTextEdit(self.frame_47)
        self.l2.setGeometry(QtCore.QRect(10, 72, 570, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.l2.setFont(font)
        self.l2.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.l2.setReadOnly(True)
        self.l2.setOverwriteMode(False)
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QPlainTextEdit(self.frame_47)
        self.l3.setGeometry(QtCore.QRect(10, 107, 570, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.l3.setFont(font)
        self.l3.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.l3.setReadOnly(True)
        self.l3.setOverwriteMode(False)
        self.l3.setObjectName("l3")
        self.l4 = QtWidgets.QPlainTextEdit(self.frame_47)
        self.l4.setGeometry(QtCore.QRect(10, 142, 570, 188))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.l4.setFont(font)
        self.l4.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.l4.setReadOnly(True)
        self.l4.setOverwriteMode(False)
        self.l4.setObjectName("l4")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(605, 0, 595, 223))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("QFrame#frame_3 { \n"
"border-radius: 5px; /* Set rounded corners */ \n"
"background-color: #ecedee; /* Set background color */ \n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_18 = QtWidgets.QFrame(self.frame_3)
        self.frame_18.setGeometry(QtCore.QRect(5, 5, 585, 213))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.frame_18.setFont(font)
        self.frame_18.setStyleSheet("/* QLabel Default style */\n"
"QLabel {\n"
"    color:  #000000; /* Text color */\n"
"    font-size: 16px; /* Font size */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"QFrame#frame_18 {\n"
"    background-color: #ffffff; /* Set background color */ \n"
"    border-radius: 5px;\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_19 = QtWidgets.QLabel(self.frame_18)
        self.label_19.setGeometry(QtCore.QRect(10, 5, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(220, 0))
        self.label_19.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("/* QLabel Default style */\n"
"QLabel#label_19 {\n"
"    color: #000000; /* Text color */\n"
"    font-size: 24px; /* Font size */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}")
        self.label_19.setObjectName("label_19")
        self.s1 = QtWidgets.QPlainTextEdit(self.frame_18)
        self.s1.setGeometry(QtCore.QRect(10, 37, 565, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s1.setFont(font)
        self.s1.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.s1.setReadOnly(True)
        self.s1.setOverwriteMode(False)
        self.s1.setObjectName("s1")
        self.s2 = QtWidgets.QPlainTextEdit(self.frame_18)
        self.s2.setGeometry(QtCore.QRect(10, 72, 565, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s2.setFont(font)
        self.s2.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.s2.setReadOnly(True)
        self.s2.setOverwriteMode(False)
        self.s2.setObjectName("s2")
        self.s3 = QtWidgets.QPlainTextEdit(self.frame_18)
        self.s3.setGeometry(QtCore.QRect(10, 107, 565, 101))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s3.setFont(font)
        self.s3.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.s3.setReadOnly(True)
        self.s3.setOverwriteMode(False)
        self.s3.setObjectName("s3")
        self.frame_19 = QtWidgets.QFrame(Form)
        self.frame_19.setGeometry(QtCore.QRect(605, 630, 595, 170))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame_19.setFont(font)
        self.frame_19.setStyleSheet("QFrame#frame_19 { \n"
"border-radius: 5px; /* Set rounded corners */ \n"
"background-color: #ecedee; /* Set background color */ \n"
"}")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.frame_24 = QtWidgets.QFrame(self.frame_19)
        self.frame_24.setGeometry(QtCore.QRect(5, 5, 585, 160))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.frame_24.setFont(font)
        self.frame_24.setStyleSheet("/* QLabel Default style */\n"
"QLabel {\n"
"    color:  #000000; /* Text color */\n"
"    font-size: 16px; /* Font size */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"QFrame#frame_24 {\n"
"    background-color: #ffffff; /* Set background color */ \n"
"    border-radius: 5px;\n"
"}")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.label_52 = QtWidgets.QLabel(self.frame_24)
        self.label_52.setGeometry(QtCore.QRect(10, 5, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_52.sizePolicy().hasHeightForWidth())
        self.label_52.setSizePolicy(sizePolicy)
        self.label_52.setMinimumSize(QtCore.QSize(220, 0))
        self.label_52.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("/* QLabel Default style */\n"
"QLabel#label_52 {\n"
"    color: #000000; /* Text color */\n"
"    font-size: 24px; /* Font size */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}")
        self.label_52.setObjectName("label_52")
        self.rs2 = QtWidgets.QPlainTextEdit(self.frame_24)
        self.rs2.setGeometry(QtCore.QRect(10, 72, 565, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.rs2.setFont(font)
        self.rs2.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.rs2.setReadOnly(True)
        self.rs2.setOverwriteMode(False)
        self.rs2.setObjectName("rs2")
        self.rs1 = QtWidgets.QPlainTextEdit(self.frame_24)
        self.rs1.setGeometry(QtCore.QRect(10, 37, 565, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.rs1.setFont(font)
        self.rs1.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.rs1.setReadOnly(True)
        self.rs1.setOverwriteMode(False)
        self.rs1.setObjectName("rs1")
        self.frame_25 = QtWidgets.QFrame(Form)
        self.frame_25.setGeometry(QtCore.QRect(605, 228, 595, 222))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame_25.setFont(font)
        self.frame_25.setStyleSheet("QFrame#frame_25 { \n"
"border-radius: 5px; /* Set rounded corners */ \n"
"background-color: #ecedee; /* Set background color */ \n"
"}")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.frame_40 = QtWidgets.QFrame(self.frame_25)
        self.frame_40.setGeometry(QtCore.QRect(5, 5, 585, 212))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.frame_40.setFont(font)
        self.frame_40.setStyleSheet("/* QLabel Default style */\n"
"QLabel {\n"
"    color:  #000000; /* Text color */\n"
"    font-size: 16px; /* Font size */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"QFrame#frame_40 {\n"
"    background-color: #ffffff; /* Set background color */ \n"
"    border-radius: 5px;\n"
"}")
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.label_105 = QtWidgets.QLabel(self.frame_40)
        self.label_105.setGeometry(QtCore.QRect(10, 5, 201, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_105.sizePolicy().hasHeightForWidth())
        self.label_105.setSizePolicy(sizePolicy)
        self.label_105.setMinimumSize(QtCore.QSize(0, 0))
        self.label_105.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_105.setFont(font)
        self.label_105.setStyleSheet("/* QLabel Default style */\n"
"QLabel#label_105 {\n"
"    color: #000000; /* Text color */\n"
"    font-size: 24px; /* Font size */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}")
        self.label_105.setObjectName("label_105")
        self.m3 = QtWidgets.QPlainTextEdit(self.frame_40)
        self.m3.setGeometry(QtCore.QRect(10, 107, 565, 101))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.m3.setFont(font)
        self.m3.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.m3.setReadOnly(True)
        self.m3.setOverwriteMode(False)
        self.m3.setObjectName("m3")
        self.m1 = QtWidgets.QPlainTextEdit(self.frame_40)
        self.m1.setGeometry(QtCore.QRect(10, 37, 565, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.m1.setFont(font)
        self.m1.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.m1.setReadOnly(True)
        self.m1.setOverwriteMode(False)
        self.m1.setObjectName("m1")
        self.m2 = QtWidgets.QPlainTextEdit(self.frame_40)
        self.m2.setGeometry(QtCore.QRect(10, 72, 565, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.m2.setFont(font)
        self.m2.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.m2.setReadOnly(True)
        self.m2.setOverwriteMode(False)
        self.m2.setObjectName("m2")
        self.frame_20 = QtWidgets.QFrame(Form)
        self.frame_20.setGeometry(QtCore.QRect(605, 455, 595, 170))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame_20.setFont(font)
        self.frame_20.setStyleSheet("QFrame#frame_20 { \n"
"border-radius: 5px; /* Set rounded corners */ \n"
"background-color: #ecedee; /* Set background color */ \n"
"}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.frame_37 = QtWidgets.QFrame(self.frame_20)
        self.frame_37.setGeometry(QtCore.QRect(5, 5, 585, 160))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.frame_37.setFont(font)
        self.frame_37.setStyleSheet("/* QLabel Default style */\n"
"QLabel {\n"
"    color:  #000000; /* Text color */\n"
"    font-size: 16px; /* Font size */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"QFrame#frame_37 {\n"
"    background-color: #ffffff; /* Set background color */ \n"
"    border-radius: 5px;\n"
"}")
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.label_83 = QtWidgets.QLabel(self.frame_37)
        self.label_83.setGeometry(QtCore.QRect(10, 5, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_83.sizePolicy().hasHeightForWidth())
        self.label_83.setSizePolicy(sizePolicy)
        self.label_83.setMinimumSize(QtCore.QSize(220, 0))
        self.label_83.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_83.setFont(font)
        self.label_83.setStyleSheet("/* QLabel Default style */\n"
"QLabel#label_83 {\n"
"    color: #000000; /* Text color */\n"
"    font-size: 24px; /* Font size */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}")
        self.label_83.setObjectName("label_83")
        self.p2 = QtWidgets.QPlainTextEdit(self.frame_37)
        self.p2.setGeometry(QtCore.QRect(10, 72, 565, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.p2.setFont(font)
        self.p2.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.p2.setReadOnly(True)
        self.p2.setOverwriteMode(False)
        self.p2.setObjectName("p2")
        self.p1 = QtWidgets.QPlainTextEdit(self.frame_37)
        self.p1.setGeometry(QtCore.QRect(10, 37, 565, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.p1.setFont(font)
        self.p1.setStyleSheet("QPlainTextEdit {\n"
"   \n"
"    border-radius: 5px; /* Corner radius */\n"
"    background-color: #fbfbfc; /* Background color */\n"
"    color: #333333; /* Font color */\n"
"}")
        self.p1.setReadOnly(True)
        self.p1.setOverwriteMode(False)
        self.p1.setObjectName("p1")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Station Info"))
        self.label_138.setText(_translate("Form", "Reactant Rack Info"))
        self.r1.setPlainText(_translate("Form", "Reactant Rack 1:"))
        self.r2.setPlainText(_translate("Form", "Reactant Rack 2:"))
        self.r3.setPlainText(_translate("Form", "Reactant Rack 3:"))
        self.r4.setPlainText(_translate("Form", "Reactant Rack 4:\n"
""))
        self.label_141.setText(_translate("Form", "Liquid Station"))
        self.l1.setPlainText(_translate("Form", "Reaction Bottle Rack:"))
        self.l2.setPlainText(_translate("Form", "Running Status:"))
        self.l3.setPlainText(_translate("Form", "Tip Rack:"))
        self.l4.setPlainText(_translate("Form", "Chemical Remaining:"))
        self.label_19.setText(_translate("Form", "Solid Station"))
        self.s1.setPlainText(_translate("Form", "Reaction Bottle Rack:"))
        self.s2.setPlainText(_translate("Form", "Running Status:"))
        self.s3.setPlainText(_translate("Form", "Chemical Remaining:"))
        self.label_52.setText(_translate("Form", "Reactor Station"))
        self.rs2.setPlainText(_translate("Form", "Running Status:"))
        self.rs1.setPlainText(_translate("Form", "Reaction Bottle Rack:"))
        self.label_105.setText(_translate("Form", "Mobile Robot"))
        self.m3.setPlainText(_translate("Form", "Bottle Rack Info:"))
        self.m1.setPlainText(_translate("Form", "Running Status:"))
        self.m2.setPlainText(_translate("Form", "Tip Rack Info:"))
        self.label_83.setText(_translate("Form", "Peptid Station"))
        self.p2.setPlainText(_translate("Form", "Running Status:"))
        self.p1.setPlainText(_translate("Form", "Reaction Bottle Rack:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
