# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

# Get the directory containing the generated UI assets.
ui_path = os.path.dirname(os.path.abspath(__file__))


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setWindowTitle("AutoChem")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(os.path.join(ui_path, "icon/chemistry.png")),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(
            "QMainWindow {\n"
            "    background-color: #ffffff; /* Set background color */ \n"
            "    border-radius: 20px;  /*Set corner radius*/\n"
            "}"
        )
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 230, 900))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame.setFont(font)
        self.frame.setStyleSheet(
            "QFrame#frame { \n"
            "border-radius: 5px; /* Set rounded corners */ \n"
            "background-color: #ecedee; /* Set background color */ \n"
            "}"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setGeometry(QtCore.QRect(5, 505, 220, 120))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame_10.setFont(font)
        self.frame_10.setStyleSheet(
            "/* QLabel Default style */\n"
            "QLabel {\n"
            "    color:  #000000; /* Text color */\n"
            "    font-size: 16px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "}\n"
            "QFrame#frame_10 {\n"
            "    background-color: #fbfbfc; /* Set background color */ \n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_12 = QtWidgets.QLabel(self.frame_10)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(220, 0))
        self.label_12.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(
            "/* QLabel Default style */\n"
            "QLabel#label_12\n"
            " {\n"
            "    color: #000000; /* Text color */\n"
            "    font-size: 24px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "}"
        )
        self.label_12.setObjectName("label_12")
        self.label_78 = QtWidgets.QLabel(self.frame_10)
        self.label_78.setGeometry(QtCore.QRect(10, 80, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_78.sizePolicy().hasHeightForWidth())
        self.label_78.setSizePolicy(sizePolicy)
        self.label_78.setMinimumSize(QtCore.QSize(220, 0))
        self.label_78.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_78.setFont(font)
        self.label_78.setTextFormat(QtCore.Qt.AutoText)
        self.label_78.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.frame_10)
        self.label_79.setGeometry(QtCore.QRect(10, 50, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_79.sizePolicy().hasHeightForWidth())
        self.label_79.setSizePolicy(sizePolicy)
        self.label_79.setMinimumSize(QtCore.QSize(220, 0))
        self.label_79.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_79.setFont(font)
        self.label_79.setTextFormat(QtCore.Qt.AutoText)
        self.label_79.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.label_79.setObjectName("label_79")
        self.s5 = QtWidgets.QPushButton(self.frame_10)
        self.s5.setGeometry(QtCore.QRect(180, 85, 24, 24))
        self.s5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(os.path.join(ui_path, "icon/info.png")),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.s5.setIcon(icon1)
        self.s5.setObjectName("s5")
        self.t5 = QtWidgets.QPushButton(self.frame_10)
        self.t5.setGeometry(QtCore.QRect(180, 55, 24, 24))
        self.t5.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(os.path.join(ui_path, "icon/setting.png")),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.t5.setIcon(icon2)
        self.t5.setObjectName("t5")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(5, 130, 220, 120))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame_7.setFont(font)
        self.frame_7.setStyleSheet(
            "/* QLabel Default style */\n"
            "QLabel {\n"
            "    color:  #000000; /* Text color */\n"
            "    font-size: 16px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "}\n"
            "QFrame#frame_7 {\n"
            "    background-color: #fbfbfc; /* Set background color */ \n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(220, 0))
        self.label_6.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(
            "/* QLabel Default style */\n"
            "QLabel#label_6\n"
            " {\n"
            "    color: #000000; /* Text color */\n"
            "    font-size: 24px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "}"
        )
        self.label_6.setObjectName("label_6")
        self.label_22 = QtWidgets.QLabel(self.frame_7)
        self.label_22.setGeometry(QtCore.QRect(10, 80, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(220, 0))
        self.label_22.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_22.setFont(font)
        self.label_22.setTextFormat(QtCore.Qt.AutoText)
        self.label_22.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_7)
        self.label_23.setGeometry(QtCore.QRect(10, 50, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(220, 0))
        self.label_23.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_23.setFont(font)
        self.label_23.setTextFormat(QtCore.Qt.AutoText)
        self.label_23.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.label_23.setObjectName("label_23")
        self.s2 = QtWidgets.QPushButton(self.frame_7)
        self.s2.setGeometry(QtCore.QRect(180, 85, 24, 24))
        self.s2.setText("")
        self.s2.setIcon(icon1)
        self.s2.setObjectName("s2")
        self.t2 = QtWidgets.QPushButton(self.frame_7)
        self.t2.setGeometry(QtCore.QRect(180, 55, 24, 24))
        self.t2.setText("")
        self.t2.setIcon(icon2)
        self.t2.setObjectName("t2")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(5, 380, 220, 120))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame_9.setFont(font)
        self.frame_9.setStyleSheet(
            "/* QLabel Default style */\n"
            "QLabel {\n"
            "    color:  #000000; /* Text color */\n"
            "    font-size: 16px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "}\n"
            "QFrame#frame_9 {\n"
            "    background-color: #fbfbfc; /* Set background color */ \n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_11 = QtWidgets.QLabel(self.frame_9)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(220, 0))
        self.label_11.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(
            "/* QLabel Default style */\n"
            "QLabel#label_11\n"
            " {\n"
            "    color: #000000; /* Text color */\n"
            "    font-size: 24px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "}"
        )
        self.label_11.setObjectName("label_11")
        self.label_26 = QtWidgets.QLabel(self.frame_9)
        self.label_26.setGeometry(QtCore.QRect(10, 80, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(220, 0))
        self.label_26.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_26.setFont(font)
        self.label_26.setTextFormat(QtCore.Qt.AutoText)
        self.label_26.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.label_26.setObjectName("label_26")
        self.label_41 = QtWidgets.QLabel(self.frame_9)
        self.label_41.setGeometry(QtCore.QRect(10, 50, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setMinimumSize(QtCore.QSize(220, 0))
        self.label_41.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_41.setFont(font)
        self.label_41.setTextFormat(QtCore.Qt.AutoText)
        self.label_41.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.label_41.setObjectName("label_41")
        self.s4 = QtWidgets.QPushButton(self.frame_9)
        self.s4.setGeometry(QtCore.QRect(180, 85, 24, 24))
        self.s4.setText("")
        self.s4.setIcon(icon1)
        self.s4.setObjectName("s4")
        self.t4 = QtWidgets.QPushButton(self.frame_9)
        self.t4.setGeometry(QtCore.QRect(180, 55, 24, 24))
        self.t4.setText("")
        self.t4.setIcon(icon2)
        self.t4.setObjectName("t4")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(5, 255, 220, 120))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet(
            "/* QLabel Default style */\n"
            "QLabel {\n"
            "    color:  #000000; /* Text color */\n"
            "    font-size: 16px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "}\n"
            "QFrame#frame_4 {\n"
            "    background-color: #fbfbfc; /* Set background color */ \n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(220, 0))
        self.label_3.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(
            "/* QLabel Default style */\n"
            "QLabel#label_3\n"
            " {\n"
            "    color: #000000; /* Text color */\n"
            "    font-size: 24px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "}"
        )
        self.label_3.setObjectName("label_3")
        self.label_24 = QtWidgets.QLabel(self.frame_4)
        self.label_24.setGeometry(QtCore.QRect(10, 50, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(220, 0))
        self.label_24.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_24.setFont(font)
        self.label_24.setTextFormat(QtCore.Qt.AutoText)
        self.label_24.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_4)
        self.label_25.setGeometry(QtCore.QRect(10, 80, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(220, 0))
        self.label_25.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_25.setFont(font)
        self.label_25.setTextFormat(QtCore.Qt.AutoText)
        self.label_25.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.label_25.setObjectName("label_25")
        self.s3 = QtWidgets.QPushButton(self.frame_4)
        self.s3.setGeometry(QtCore.QRect(180, 85, 24, 24))
        self.s3.setText("")
        self.s3.setIcon(icon1)
        self.s3.setObjectName("s3")
        self.t3 = QtWidgets.QPushButton(self.frame_4)
        self.t3.setGeometry(QtCore.QRect(180, 55, 24, 24))
        self.t3.setText("")
        self.t3.setIcon(icon2)
        self.t3.setObjectName("t3")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(5, 5, 220, 120))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.frame_8.setFont(font)
        self.frame_8.setStyleSheet(
            "/* QLabel Default style */\n"
            "QLabel {\n"
            "    color:  #000000; /* Text color */\n"
            "    font-size: 16px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "}\n"
            "QFrame#frame_8 {\n"
            "    background-color: #fbfbfc; /* Set background color */ \n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(220, 0))
        self.label_8.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(
            "/* QLabel Default style */\n"
            "QLabel#label_8 {\n"
            "    color: #000000; /* Text color */\n"
            "    font-size: 24px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "}"
        )
        self.label_8.setObjectName("label_8")
        self.label_15 = QtWidgets.QLabel(self.frame_8)
        self.label_15.setGeometry(QtCore.QRect(10, 50, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(220, 0))
        self.label_15.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_15.setFont(font)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.label_15.setObjectName("label_15")
        self.label_21 = QtWidgets.QLabel(self.frame_8)
        self.label_21.setGeometry(QtCore.QRect(10, 80, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(220, 0))
        self.label_21.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_21.setFont(font)
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.label_21.setObjectName("label_21")
        self.t1 = QtWidgets.QPushButton(self.frame_8)
        self.t1.setGeometry(QtCore.QRect(180, 55, 24, 24))
        self.t1.setText("")
        self.t1.setIcon(icon2)
        self.t1.setObjectName("t1")
        self.s1 = QtWidgets.QPushButton(self.frame_8)
        self.s1.setGeometry(QtCore.QRect(180, 85, 24, 24))
        self.s1.setText("")
        self.s1.setIcon(icon1)
        self.s1.setObjectName("s1")
        self.file = QtWidgets.QPushButton(self.frame)
        self.file.setGeometry(QtCore.QRect(5, 845, 220, 50))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file.sizePolicy().hasHeightForWidth())
        self.file.setSizePolicy(sizePolicy)
        self.file.setMinimumSize(QtCore.QSize(220, 50))
        self.file.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.file.setFont(font)
        self.file.setStyleSheet(
            "/* QPushButton Default state */\n"
            "QPushButton {\n"
            "    background-color: #87CEEB; /* Light blue background */\n"
            "    color: white; /* White text */\n"
            "    border: none; /* Remove border */\n"
            "    padding: 10px; /* Set padding */\n"
            "    border-radius: 5px; /* Set rounded corners */\n"
            "}\n"
            "\n"
            "/* QPushButton Focus state */\n"
            "QPushButton:focus {\n"
            "    background-color: #4682B4; /* Medium blue background */\n"
            "    color: white; /* Focus stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Hover state */\n"
            "QPushButton:hover {\n"
            "    background-color: #87CEff; /* Dark blue background */\n"
            "    color: white; /* Hover stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Pressed state */\n"
            "QPushButton:pressed {\n"
            "    background-color: #4A90E2; /* Darker blue background when pressed */\n"
            "    color: white; /* Pressed stateWhite text */\n"
            "}"
        )
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(os.path.join(ui_path, "icon/file.png")),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.file.setIcon(icon3)
        self.file.setIconSize(QtCore.QSize(25, 25))
        self.file.setShortcut("")
        self.file.setAutoDefault(False)
        self.file.setDefault(False)
        self.file.setFlat(False)
        self.file.setObjectName("file")
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setGeometry(QtCore.QRect(5, 630, 220, 210))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame_11.setFont(font)
        self.frame_11.setStyleSheet(
            "QFrame#frame_11 {\n"
            "    background-color: #fbfbfc; /* Set background color */\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QLabel {\n"
            "    color: #000000; /* Text color */\n"
            "    font-size: 24px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "}"
        )
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_13 = QtWidgets.QLabel(self.frame_11)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(220, 0))
        self.label_13.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.task = QtWidgets.QPlainTextEdit(self.frame_11)
        self.task.setGeometry(QtCore.QRect(10, 55, 200, 145))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.task.setFont(font)
        self.task.setStyleSheet(
            "QPlainTextEdit {\n"
            "   \n"
            "    border-radius: 5px; /* Corner radius */\n"
            "    background-color: #ffffff; /* Background color */\n"
            "    color: #333333; /* Font color */\n"
            "}"
        )
        self.task.setReadOnly(True)
        self.task.setPlainText("")
        self.task.setOverwriteMode(False)
        self.task.setObjectName("task")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(235, 0, 965, 900))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet(
            "QFrame#frame_2 {\n"
            "    background-color: #ecedee; /* Set background color */ \n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(5, 5, 295, 120))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet(
            "QFrame#frame_3 {\n"
            "    background-color: #fbfbfc; /* Set background color */ \n"
            "    border-radius: 5px;\n"
            "}\n"
            "\n"
            ""
        )
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pre = QtWidgets.QCheckBox(self.frame_3)
        self.pre.setGeometry(QtCore.QRect(20, 46, 175, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pre.setFont(font)
        self.pre.setStyleSheet(
            "QCheckBox {\n"
            "    color: #000000; /* Text color */\n"
            "    font-size: 20px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "}\n"
            "QCheckBox::indicator:checked {\n"
            "    background-color: rgb(255, 247, 148); /* Selected checkbox background color */\n"
            "    border: 1px solid #000000; /* Selected checkbox border color */\n"
            "    border-radius: 4px; /* Rounded corners */\n"
            "}"
        )
        self.pre.setObjectName("pre")
        self.post = QtWidgets.QCheckBox(self.frame_3)
        self.post.setGeometry(QtCore.QRect(20, 78, 190, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.post.setFont(font)
        self.post.setStyleSheet(
            "QCheckBox {\n"
            "    color: #000000; /* Text color */\n"
            "    font-size: 20px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "}\n"
            "QCheckBox::indicator:checked {\n"
            "    background-color: #4A90E2; /* Selected checkbox background color */\n"
            "    border: 1px solid #000000; /* Selected checkbox border color */\n"
            "    border-radius: 4px; /* Rounded corners */\n"
            "}"
        )
        self.post.setObjectName("post")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 260, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(220, 0))
        self.label_9.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(
            "QLabel {\n"
            "    color: #000000; /* Text color */\n"
            "    font-size: 24px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "    qproperty-alignment: 'AlignCenter';\n"
            "}"
        )
        self.label_9.setObjectName("label_9")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setEnabled(True)
        self.frame_5.setGeometry(QtCore.QRect(5, 130, 955, 495))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame_5.setFont(font)
        self.frame_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame_5.setStyleSheet(
            "QFrame#frame_5 {\n"
            "    background-color: #fbfbfc; /* Set background color */ \n"
            "    border-radius: 5px;\n"
            "}\n"
            "QLabel {\n"
            "    border: 1px dashed #000000;\n"
            "    border-radius: 10px;\n"
            "}"
        )
        self.frame_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(427, 197, 100, 100))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet(
            "QLabel {\n"
            "    qproperty-alignment: 'AlignCenter';\n"
            "    qproperty-scaledContents: 1;\n"
            "}"
        )
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(ui_path, "icon/robot.png")))
        self.label.setObjectName("label")
        self.liquid = QtWidgets.QLabel(self.frame_5)
        self.liquid.setGeometry(QtCore.QRect(565, 20, 100, 100))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.liquid.setFont(font)
        self.liquid.setStyleSheet(
            "QLabel {\n"
            "    qproperty-alignment: 'AlignCenter';\n"
            "    qproperty-scaledContents: 1;\n"
            "}"
        )
        self.liquid.setText("")
        self.liquid.setPixmap(QtGui.QPixmap(os.path.join(ui_path, "icon/liquid.png")))
        self.liquid.setObjectName("liquid")
        self.solid = QtWidgets.QLabel(self.frame_5)
        self.solid.setGeometry(QtCore.QRect(290, 375, 100, 100))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.solid.setFont(font)
        self.solid.setStyleSheet(
            "QLabel {\n"
            "    qproperty-alignment: 'AlignCenter';\n"
            "    qproperty-scaledContents: 1;\n"
            "}"
        )
        self.solid.setText("")
        self.solid.setPixmap(QtGui.QPixmap(os.path.join(ui_path, "icon/solid.png")))
        self.solid.setObjectName("solid")
        self.reactor = QtWidgets.QLabel(self.frame_5)
        self.reactor.setGeometry(QtCore.QRect(290, 20, 100, 100))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.reactor.setFont(font)
        self.reactor.setStyleSheet(
            "QLabel {\n"
            "    qproperty-alignment: 'AlignCenter';\n"
            "    qproperty-scaledContents: 1;\n"
            "}"
        )
        self.reactor.setText("")
        self.reactor.setPixmap(QtGui.QPixmap(os.path.join(ui_path, "icon/reactor.png")))
        self.reactor.setObjectName("reactor")
        self.nmr = QtWidgets.QLabel(self.frame_5)
        self.nmr.setGeometry(QtCore.QRect(835, 20, 100, 100))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.nmr.setFont(font)
        self.nmr.setStyleSheet(
            "QLabel {\n"
            "    qproperty-alignment: 'AlignCenter';\n"
            "    qproperty-scaledContents: 1;\n"
            "}"
        )
        self.nmr.setText("")
        self.nmr.setPixmap(QtGui.QPixmap(os.path.join(ui_path, "icon/nmr.png")))
        self.nmr.setObjectName("nmr")
        self.peptide = QtWidgets.QLabel(self.frame_5)
        self.peptide.setGeometry(QtCore.QRect(565, 375, 100, 100))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.peptide.setFont(font)
        self.peptide.setStyleSheet(
            "QLabel {\n"
            "    qproperty-alignment: 'AlignCenter';\n"
            "    qproperty-scaledContents: 1;\n"
            "}"
        )
        self.peptide.setText("")
        self.peptide.setPixmap(QtGui.QPixmap(os.path.join(ui_path, "icon/peptide.png")))
        self.peptide.setObjectName("peptide")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 100, 100))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(
            "QLabel {\n"
            "    qproperty-alignment: 'AlignCenter';\n"
            "    qproperty-scaledContents: 1;\n"
            "}"
        )
        self.label_7.setText("")
        self.label_7.setPixmap(
            QtGui.QPixmap(os.path.join(ui_path, "icon/charging.png"))
        )
        self.label_7.setObjectName("label_7")
        self.label_17 = QtWidgets.QLabel(self.frame_5)
        self.label_17.setGeometry(QtCore.QRect(20, 375, 100, 100))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet(
            "QLabel {\n"
            "    qproperty-alignment: 'AlignCenter';\n"
            "    qproperty-scaledContents: 1;\n"
            "}"
        )
        self.label_17.setText("")
        self.label_17.setPixmap(
            QtGui.QPixmap(os.path.join(ui_path, "icon/transfer.png"))
        )
        self.label_17.setObjectName("label_17")
        self.r11 = QtWidgets.QFrame(self.frame_5)
        self.r11.setGeometry(QtCore.QRect(70, 247, 357, 1))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.r11.setFont(font)
        self.r11.setStyleSheet(
            "Qframe#frame_13 {\n" "    border: 1px dashed black;\n" "}"
        )
        self.r11.setFrameShape(QtWidgets.QFrame.HLine)
        self.r11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r11.setLineWidth(1)
        self.r11.setMidLineWidth(0)
        self.r11.setObjectName("r11")
        self.h11 = QtWidgets.QFrame(self.frame_5)
        self.h11.setGeometry(QtCore.QRect(69, 120, 2, 127))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.h11.setFont(font)
        self.h11.setStyleSheet(
            "Qframe#frame_13 {\n" "    border: 1px dashed black;\n" "}"
        )
        self.h11.setFrameShape(QtWidgets.QFrame.VLine)
        self.h11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.h11.setLineWidth(1)
        self.h11.setMidLineWidth(0)
        self.h11.setObjectName("h11")
        self.h12 = QtWidgets.QFrame(self.frame_5)
        self.h12.setGeometry(QtCore.QRect(69, 247, 2, 128))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.h12.setFont(font)
        self.h12.setStyleSheet(
            "Qframe#frame_13 {\n" "    border: 1px dashed black;\n" "}"
        )
        self.h12.setFrameShape(QtWidgets.QFrame.VLine)
        self.h12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.h12.setLineWidth(1)
        self.h12.setMidLineWidth(0)
        self.h12.setObjectName("h12")
        self.r21 = QtWidgets.QFrame(self.frame_5)
        self.r21.setGeometry(QtCore.QRect(527, 247, 360, 1))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.r21.setFont(font)
        self.r21.setStyleSheet(
            "Qframe#frame_13 {\n" "    border: 1px dashed black;\n" "}"
        )
        self.r21.setFrameShape(QtWidgets.QFrame.HLine)
        self.r21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r21.setLineWidth(1)
        self.r21.setMidLineWidth(0)
        self.r21.setObjectName("r21")

        self.r22 = QtWidgets.QFrame(self.frame_5)
        self.r22.setGeometry(QtCore.QRect(527, 247, 88, 1))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.r22.setFont(font)
        self.r22.setStyleSheet(
            "Qframe#frame_13 {\n" "    border: 1px dashed black;\n" "}"
        )
        self.r22.setFrameShape(QtWidgets.QFrame.HLine)
        self.r22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r22.setLineWidth(1)
        self.r22.setMidLineWidth(0)
        self.r22.setObjectName("r22")

        self.h41 = QtWidgets.QFrame(self.frame_5)
        self.h41.setGeometry(QtCore.QRect(885, 120, 2, 127))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.h41.setFont(font)
        self.h41.setStyleSheet(
            "Qframe#frame_13 {\n" "    border: 1px dashed black;\n" "}"
        )
        self.h41.setFrameShape(QtWidgets.QFrame.VLine)
        self.h41.setFrameShadow(QtWidgets.QFrame.Plain)
        self.h41.setLineWidth(1)
        self.h41.setMidLineWidth(0)
        self.h41.setObjectName("h41")
        self.h21 = QtWidgets.QFrame(self.frame_5)
        self.h21.setGeometry(QtCore.QRect(338, 120, 2, 127))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.h21.setFont(font)
        self.h21.setStyleSheet(
            "Qframe#frame_13 {\n" "    border: 1px dashed black;\n" "}"
        )
        self.h21.setFrameShape(QtWidgets.QFrame.VLine)
        self.h21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.h21.setLineWidth(1)
        self.h21.setMidLineWidth(0)
        self.h21.setObjectName("h21")
        self.r12 = QtWidgets.QFrame(self.frame_5)
        self.r12.setGeometry(QtCore.QRect(339, 247, 88, 1))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.r12.setFont(font)
        self.r12.setStyleSheet(
            "Qframe#frame_13 {\n" "    border: 1px dashed black;\n" "}"
        )
        self.r12.setFrameShape(QtWidgets.QFrame.HLine)
        self.r12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r12.setLineWidth(1)
        self.r12.setMidLineWidth(0)
        self.r12.setObjectName("r12")
        self.h22 = QtWidgets.QFrame(self.frame_5)
        self.h22.setGeometry(QtCore.QRect(338, 247, 2, 128))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.h22.setFont(font)
        self.h22.setStyleSheet(
            "Qframe#frame_13 {\n" "    border: 1px dashed black;\n" "}"
        )
        self.h22.setFrameShape(QtWidgets.QFrame.VLine)
        self.h22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.h22.setLineWidth(1)
        self.h22.setMidLineWidth(0)
        self.h22.setObjectName("h22")
        self.h31 = QtWidgets.QFrame(self.frame_5)
        self.h31.setGeometry(QtCore.QRect(613, 120, 2, 127))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.h31.setFont(font)
        self.h31.setStyleSheet(
            "Qframe#frame_13 {\n" "    border: 1px dashed black;\n" "}"
        )
        self.h31.setFrameShape(QtWidgets.QFrame.VLine)
        self.h31.setFrameShadow(QtWidgets.QFrame.Plain)
        self.h31.setLineWidth(1)
        self.h31.setMidLineWidth(0)
        self.h31.setObjectName("h31")
        self.h32 = QtWidgets.QFrame(self.frame_5)
        self.h32.setGeometry(QtCore.QRect(613, 247, 2, 128))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.h32.setFont(font)
        self.h32.setStyleSheet(
            "Qframe#frame_13 {\n" "    border: 1px dashed black;\n" "}"
        )
        self.h32.setFrameShape(QtWidgets.QFrame.VLine)
        self.h32.setFrameShadow(QtWidgets.QFrame.Plain)
        self.h32.setLineWidth(1)
        self.h32.setMidLineWidth(0)
        self.h32.setObjectName("h32")
        self.frame_13 = QtWidgets.QFrame(self.frame_5)
        self.frame_13.setGeometry(QtCore.QRect(710, 293, 220, 182))
        self.frame_13.setStyleSheet(
            "QFrame#frame_13 {\n"
            "    background-color: white; /* Set background color */ \n"
            "    border-radius: 5px;\n"
            "    border: 1px dashed black;\n"
            "}\n"
            "QPushButton {\n"
            "    text-align: left;\n"
            "    padding: 6px;\n"
            "}"
        )
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.stop1 = QtWidgets.QPushButton(self.frame_13)
        self.stop1.setGeometry(QtCore.QRect(5, 5, 210, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop1.sizePolicy().hasHeightForWidth())
        self.stop1.setSizePolicy(sizePolicy)
        self.stop1.setMinimumSize(QtCore.QSize(150, 32))
        self.stop1.setMaximumSize(QtCore.QSize(22222, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.stop1.setFont(font)
        self.stop1.setStyleSheet(
            "/* QPushButton Default state */\n"
            "QPushButton {\n"
            "    background-color: #2E2E2E; /* Light blue background */\n"
            "    color: white; /* White text */\n"
            "    border: none; /* Remove border */\n"
            "    border-radius: 5px; /* Set rounded corners */\n"
            "}\n"
            "\n"
            "/* QPushButton Focus state */\n"
            "QPushButton:focus {\n"
            "    background-color: #474747; /* Medium blue background */\n"
            "    color: white; /* Focus stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Hover state */\n"
            "QPushButton:hover {\n"
            "    background-color: #474747; /* Dark blue background */\n"
            "    color: white; /* Hover stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Pressed state */\n"
            "QPushButton:pressed {\n"
            "    background-color: #1C1C1C; /* Darker blue background when pressed */\n"
            "    color: white; /* Pressed stateWhite text */\n"
            "}"
        )
        icon_stop = QtGui.QIcon()
        icon_stop.addPixmap(
            QtGui.QPixmap(os.path.join(ui_path, "icon/stop.png")),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.stop1.setIcon(icon_stop)
        self.stop1.setIconSize(QtCore.QSize(25, 25))
        self.stop1.setShortcut("")
        self.stop1.setAutoDefault(False)
        self.stop1.setDefault(False)
        self.stop1.setFlat(False)
        self.stop1.setObjectName("stop1")
        self.stop2 = QtWidgets.QPushButton(self.frame_13)
        self.stop2.setGeometry(QtCore.QRect(5, 40, 210, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop2.sizePolicy().hasHeightForWidth())
        self.stop2.setSizePolicy(sizePolicy)
        self.stop2.setMinimumSize(QtCore.QSize(150, 32))
        self.stop2.setMaximumSize(QtCore.QSize(22222, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.stop2.setFont(font)
        self.stop2.setStyleSheet(
            "/* QPushButton Default state */\n"
            "QPushButton {\n"
            "    background-color: #2E2E2E; /* Light blue background */\n"
            "    color: white; /* White text */\n"
            "    border: none; /* Remove border */\n"
            "    border-radius: 5px; /* Set rounded corners */\n"
            "}\n"
            "\n"
            "/* QPushButton Focus state */\n"
            "QPushButton:focus {\n"
            "    background-color: #474747; /* Medium blue background */\n"
            "    color: white; /* Focus stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Hover state */\n"
            "QPushButton:hover {\n"
            "    background-color: #474747; /* Dark blue background */\n"
            "    color: white; /* Hover stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Pressed state */\n"
            "QPushButton:pressed {\n"
            "    background-color: #1C1C1C; /* Darker blue background when pressed */\n"
            "    color: white; /* Pressed stateWhite text */\n"
            "}"
        )
        self.stop2.setIcon(icon_stop)
        self.stop2.setIconSize(QtCore.QSize(25, 25))
        self.stop2.setShortcut("")
        self.stop2.setAutoDefault(False)
        self.stop2.setDefault(False)
        self.stop2.setFlat(False)
        self.stop2.setObjectName("stop2")
        self.stop3 = QtWidgets.QPushButton(self.frame_13)
        self.stop3.setGeometry(QtCore.QRect(5, 75, 210, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop3.sizePolicy().hasHeightForWidth())
        self.stop3.setSizePolicy(sizePolicy)
        self.stop3.setMinimumSize(QtCore.QSize(150, 32))
        self.stop3.setMaximumSize(QtCore.QSize(22222, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.stop3.setFont(font)
        self.stop3.setStyleSheet(
            "/* QPushButton Default state */\n"
            "QPushButton {\n"
            "    background-color: #2E2E2E; /* Light blue background */\n"
            "    color: white; /* White text */\n"
            "    border: none; /* Remove border */\n"
            "    border-radius: 5px; /* Set rounded corners */\n"
            "}\n"
            "\n"
            "/* QPushButton Focus state */\n"
            "QPushButton:focus {\n"
            "    background-color: #474747; /* Medium blue background */\n"
            "    color: white; /* Focus stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Hover state */\n"
            "QPushButton:hover {\n"
            "    background-color: #474747; /* Dark blue background */\n"
            "    color: white; /* Hover stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Pressed state */\n"
            "QPushButton:pressed {\n"
            "    background-color: #1C1C1C; /* Darker blue background when pressed */\n"
            "    color: white; /* Pressed stateWhite text */\n"
            "}"
        )
        self.stop3.setIcon(icon_stop)
        self.stop3.setIconSize(QtCore.QSize(25, 25))
        self.stop3.setShortcut("")
        self.stop3.setAutoDefault(False)
        self.stop3.setDefault(False)
        self.stop3.setFlat(False)
        self.stop3.setObjectName("stop3")
        self.stop5 = QtWidgets.QPushButton(self.frame_13)
        self.stop5.setGeometry(QtCore.QRect(5, 145, 210, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop5.sizePolicy().hasHeightForWidth())
        self.stop5.setSizePolicy(sizePolicy)
        self.stop5.setMinimumSize(QtCore.QSize(150, 32))
        self.stop5.setMaximumSize(QtCore.QSize(22222, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.stop5.setFont(font)
        self.stop5.setStyleSheet(
            "/* QPushButton Default state */\n"
            "QPushButton {\n"
            "    background-color: #2E2E2E; /* Light blue background */\n"
            "    color: white; /* White text */\n"
            "    border: none; /* Remove border */\n"
            "    border-radius: 5px; /* Set rounded corners */\n"
            "}\n"
            "\n"
            "/* QPushButton Focus state */\n"
            "QPushButton:focus {\n"
            "    background-color: #474747; /* Medium blue background */\n"
            "    color: white; /* Focus stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Hover state */\n"
            "QPushButton:hover {\n"
            "    background-color: #474747; /* Dark blue background */\n"
            "    color: white; /* Hover stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Pressed state */\n"
            "QPushButton:pressed {\n"
            "    background-color: #1C1C1C; /* Darker blue background when pressed */\n"
            "    color: white; /* Pressed stateWhite text */\n"
            "}"
        )
        self.stop5.setIcon(icon_stop)
        self.stop5.setIconSize(QtCore.QSize(25, 25))
        self.stop5.setShortcut("")
        self.stop5.setAutoDefault(False)
        self.stop5.setDefault(False)
        self.stop5.setFlat(False)
        self.stop5.setObjectName("stop5")
        self.stop4 = QtWidgets.QPushButton(self.frame_13)
        self.stop4.setGeometry(QtCore.QRect(5, 110, 210, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop4.sizePolicy().hasHeightForWidth())
        self.stop4.setSizePolicy(sizePolicy)
        self.stop4.setMinimumSize(QtCore.QSize(150, 32))
        self.stop4.setMaximumSize(QtCore.QSize(22222, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.stop4.setFont(font)
        self.stop4.setStyleSheet(
            "/* QPushButton Default state */\n"
            "QPushButton {\n"
            "    background-color: #2E2E2E; /* Light blue background */\n"
            "    color: white; /* White text */\n"
            "    border: none; /* Remove border */\n"
            "    border-radius: 5px; /* Set rounded corners */\n"
            "}\n"
            "\n"
            "/* QPushButton Focus state */\n"
            "QPushButton:focus {\n"
            "    background-color: #474747; /* Medium blue background */\n"
            "    color: white; /* Focus stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Hover state */\n"
            "QPushButton:hover {\n"
            "    background-color: #474747; /* Dark blue background */\n"
            "    color: white; /* Hover stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Pressed state */\n"
            "QPushButton:pressed {\n"
            "    background-color: #1C1C1C; /* Darker blue background when pressed */\n"
            "    color: white; /* Pressed stateWhite text */\n"
            "}"
        )
        self.stop4.setIcon(icon_stop)
        self.stop4.setIconSize(QtCore.QSize(25, 25))
        self.stop4.setShortcut("")
        self.stop4.setAutoDefault(False)
        self.stop4.setDefault(False)
        self.stop4.setFlat(False)
        self.stop4.setObjectName("stop4")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(5, 630, 955, 265))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame_6.setFont(font)
        self.frame_6.setStyleSheet(
            "QFrame#frame_6 {\n"
            "    background-color: #fbfbfc; /* Set background color */ \n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_14 = QtWidgets.QLabel(self.frame_6)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 331, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(220, 0))
        self.label_14.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(
            "QLabel {\n"
            "    color: #000000; /* Text color */\n"
            "    font-size: 24px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "    qproperty-alignment: 'AlignCenter';\n"
            "}"
        )
        self.label_14.setObjectName("label_14")
        self.details = QtWidgets.QPlainTextEdit(self.frame_6)
        self.details.setGeometry(QtCore.QRect(10, 50, 935, 205))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.details.setFont(font)
        self.details.setStyleSheet(
            "QPlainTextEdit {\n"
            "   \n"
            "    border-radius: 5px; /* Corner radius */\n"
            "    background-color: #ffffff; /* Background color */\n"
            "    color: #333333; /* Font color */\n"
            "    font-family: 'Microsoft YaHei'; /* Font */\n"
            "    font-size: 18px; /* Font size */\n"
            "    font-weight: bold; /* Font weight */\n"
            "}"
        )
        self.details.setReadOnly(True)
        self.details.setPlainText("")
        self.details.setOverwriteMode(False)
        self.details.setObjectName("details")
        self.frame_12 = QtWidgets.QFrame(self.frame_2)
        self.frame_12.setGeometry(QtCore.QRect(305, 5, 655, 120))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame_12.setFont(font)
        self.frame_12.setStyleSheet(
            "QFrame#frame_12 {\n"
            "    background-color: #fbfbfc; /* Set background color */ \n"
            "    border-radius: 5px;\n"
            "}\n"
            "QLabel {\n"
            "    color: #000000; /* Text color */\n"
            "    font-size: 18px; /* Font size */\n"
            "    height: 100px;\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "    qproperty-alignment: 'AlignCenter | AlignBottom'; /* Set alignment with qproperty-alignment */\n"
            "    font-family: 'Microsoft YaHei'; /* Font set to Microsoft YaHei */\n"
            "    font-weight: bold; /* Set bold font */\n"
            "}\n"
            "QRadioButton {\n"
            "    color: #000000; /* Text color */\n"
            "    font-size: 18px; /* Font size */\n"
            "    height: 100px;\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "    qproperty-alignment: 'AlignCenter | AlignBottom'; /* Set alignment with qproperty-alignment */\n"
            "    font-family: 'Microsoft YaHei'; /* Font set to Microsoft YaHei */\n"
            "    font-weight: bold; /* Set bold font */\n"
            "}\n"
            "\n"
            "QRadioButton::indicator:checked {\n"
            "    border: 2px solid #4A90E2; /* Border color when selected */\n"
            "}\n"
            "QCheckBox {\n"
            "    color: #000000; /* Text color */\n"
            "    font-size: 18px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "}\n"
            "QCheckBox::indicator:checked {\n"
            "    background-color: #4A90E2; /* Selected checkbox background color */\n"
            "    border: 1px solid #000000; /* Selected checkbox border color */\n"
            "    border-radius: 4px; /* Rounded corners */\n"
            "}\n"
            ""
        )
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_10 = QtWidgets.QLabel(self.frame_12)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 291, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(220, 0))
        self.label_10.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(
            "QLabel#label_10 {\n"
            "    color: #000000; /* Text color */\n"
            "    font-size: 24px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "    qproperty-alignment: 'AlignCenter';\n"
            "}"
        )
        self.label_10.setObjectName("label_10")
        self.c1 = QtWidgets.QCheckBox(self.frame_12)
        self.c1.setGeometry(QtCore.QRect(20, 46, 101, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.c1.setFont(font)
        self.c1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c1.setAutoFillBackground(False)
        self.c1.setChecked(False)
        self.c1.setAutoExclusive(False)
        self.c1.setObjectName("c1")
        self.c2 = QtWidgets.QCheckBox(self.frame_12)
        self.c2.setGeometry(QtCore.QRect(131, 46, 102, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.c2.setFont(font)
        self.c2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c2.setAutoFillBackground(False)
        self.c2.setChecked(False)
        self.c2.setAutoExclusive(False)
        self.c2.setObjectName("c2")
        self.c3 = QtWidgets.QCheckBox(self.frame_12)
        self.c3.setGeometry(QtCore.QRect(242, 46, 70, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.c3.setFont(font)
        self.c3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c3.setAutoFillBackground(False)
        self.c3.setChecked(False)
        self.c3.setAutoExclusive(False)
        self.c3.setObjectName("c3")
        self.c4 = QtWidgets.QCheckBox(self.frame_12)
        self.c4.setGeometry(QtCore.QRect(322, 46, 100, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.c4.setFont(font)
        self.c4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c4.setAutoFillBackground(False)
        self.c4.setIconSize(QtCore.QSize(16, 16))
        self.c4.setChecked(False)
        self.c4.setAutoExclusive(False)
        self.c4.setObjectName("c4")
        self.c5 = QtWidgets.QCheckBox(self.frame_12)
        self.c5.setGeometry(QtCore.QRect(432, 46, 91, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.c5.setFont(font)
        self.c5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c5.setAutoFillBackground(False)
        self.c5.setChecked(False)
        self.c5.setAutoExclusive(False)
        self.c5.setObjectName("c5")
        self.c6 = QtWidgets.QCheckBox(self.frame_12)
        self.c6.setGeometry(QtCore.QRect(533, 46, 101, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.c6.setFont(font)
        self.c6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c6.setAutoFillBackground(False)
        self.c6.setStyleSheet(
            "QCheckBox#c6::indicator:checked {\n"
            "    background-color: rgb(255, 247, 148); /* Selected checkbox background color */\n"
            "    border: 1px solid #000000; /* Selected checkbox border color */\n"
            "    border-radius: 4px; /* Rounded corners */\n"
            "}"
        )
        self.c6.setChecked(False)
        self.c6.setAutoExclusive(False)
        self.c6.setObjectName("c6")
        self.c7 = QtWidgets.QCheckBox(self.frame_12)
        self.c7.setGeometry(QtCore.QRect(20, 79, 69, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.c7.setFont(font)
        self.c7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c7.setAutoFillBackground(False)
        self.c7.setStyleSheet(
            "QCheckBox#c7::indicator:checked {\n"
            "    background-color: rgb(255, 247, 148); /* Selected checkbox background color */\n"
            "    border: 1px solid #000000; /* Selected checkbox border color */\n"
            "    border-radius: 4px; /* Rounded corners */\n"
            "}"
        )
        self.c7.setChecked(False)
        self.c7.setAutoExclusive(False)
        self.c7.setObjectName("c7")
        self.c9 = QtWidgets.QCheckBox(self.frame_12)
        self.c9.setGeometry(QtCore.QRect(201, 79, 100, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.c9.setFont(font)
        self.c9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c9.setAutoFillBackground(False)
        self.c9.setStyleSheet(
            "QCheckBox#c9::indicator:checked {\n"
            "    background-color: rgb(255, 247, 148); /* Selected checkbox background color */\n"
            "    border: 1px solid #000000; /* Selected checkbox border color */\n"
            "    border-radius: 4px; /* Rounded corners */\n"
            "}"
        )
        self.c9.setChecked(False)
        self.c9.setAutoExclusive(False)
        self.c9.setObjectName("c9")
        self.c8 = QtWidgets.QCheckBox(self.frame_12)
        self.c8.setGeometry(QtCore.QRect(99, 79, 92, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.c8.setFont(font)
        self.c8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c8.setAutoFillBackground(False)
        self.c8.setStyleSheet(
            "QCheckBox#c8::indicator:checked {\n"
            "    background-color: rgb(255, 247, 148); /* Selected checkbox background color */\n"
            "    border: 1px solid #000000; /* Selected checkbox border color */\n"
            "    border-radius: 4px; /* Rounded corners */\n"
            "}"
        )
        self.c8.setChecked(False)
        self.c8.setAutoExclusive(False)
        self.c8.setObjectName("c8")
        self.c10 = QtWidgets.QCheckBox(self.frame_12)
        self.c10.setGeometry(QtCore.QRect(311, 79, 101, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.c10.setFont(font)
        self.c10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c10.setAutoFillBackground(False)
        self.c10.setChecked(False)
        self.c10.setAutoExclusive(False)
        self.c10.setObjectName("c10")
        self.c11 = QtWidgets.QCheckBox(self.frame_12)
        self.c11.setGeometry(QtCore.QRect(422, 79, 102, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.c11.setFont(font)
        self.c11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c11.setAutoFillBackground(False)
        self.c11.setChecked(False)
        self.c11.setAutoExclusive(False)
        self.c11.setObjectName("c11")
        self.c12 = QtWidgets.QCheckBox(self.frame_12)
        self.c12.setGeometry(QtCore.QRect(534, 79, 100, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.c12.setFont(font)
        self.c12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c12.setAutoFillBackground(False)
        self.c12.setChecked(False)
        self.c12.setAutoExclusive(False)
        self.c12.setObjectName("c12")
        self.start = QtWidgets.QPushButton(self.frame_12)
        self.start.setGeometry(QtCore.QRect(484, 8, 150, 40))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        self.start.setMinimumSize(QtCore.QSize(150, 40))
        self.start.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.start.setFont(font)
        self.start.setStyleSheet(
            "/* QPushButton Default state */\n"
            "QPushButton {\n"
            "    background-color: #87CEEB; /* Light blue background */\n"
            "    color: white; /* White text */\n"
            "    border: none; /* Remove border */\n"
            "    border-radius: 5px; /* Set rounded corners */\n"
            "}\n"
            "\n"
            "/* QPushButton Focus state */\n"
            "QPushButton:focus {\n"
            "    background-color: #4682B4; /* Medium blue background */\n"
            "    color: white; /* Focus stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Hover state */\n"
            "QPushButton:hover {\n"
            "    background-color: #87CEff; /* Dark blue background */\n"
            "    color: white; /* Hover stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Pressed state */\n"
            "QPushButton:pressed {\n"
            "    background-color: #4A90E2; /* Darker blue background when pressed */\n"
            "    color: white; /* Pressed stateWhite text */\n"
            "}"
        )
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(os.path.join(ui_path, "icon/running.png")),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.start.setIcon(icon4)
        self.start.setIconSize(QtCore.QSize(25, 25))
        self.start.setShortcut("")
        self.start.setAutoDefault(False)
        self.start.setDefault(False)
        self.start.setFlat(False)
        self.start.setObjectName("start")

        self.emergency = QtWidgets.QPushButton(self.frame_12)
        self.emergency.setGeometry(QtCore.QRect(332, 8, 121, 40))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emergency.sizePolicy().hasHeightForWidth())
        self.emergency.setSizePolicy(sizePolicy)
        self.emergency.setMinimumSize(QtCore.QSize(0, 32))
        self.emergency.setMaximumSize(QtCore.QSize(161, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.emergency.setFont(font)
        self.emergency.setStyleSheet(
            "/* QPushButton Default state */\n"
            "QPushButton {\n"
            "    background-color: #2E2E2E; /* Light blue background */\n"
            "    color: white; /* White text */\n"
            "    border: none; /* Remove border */\n"
            "    border-radius: 5px; /* Set rounded corners */\n"
            "}\n"
            "\n"
            "/* QPushButton Focus state */\n"
            "QPushButton:focus {\n"
            "    background-color: #474747; /* Medium blue background */\n"
            "    color: white; /* Focus stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Hover state */\n"
            "QPushButton:hover {\n"
            "    background-color: #474747; /* Dark blue background */\n"
            "    color: white; /* Hover stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Pressed state */\n"
            "QPushButton:pressed {\n"
            "    background-color: #1C1C1C; /* Darker blue background when pressed */\n"
            "    color: white; /* Pressed stateWhite text */\n"
            "}"
        )
        self.emergency.setIcon(icon_stop)
        self.emergency.setIconSize(QtCore.QSize(25, 25))
        self.emergency.setShortcut("")
        self.emergency.setAutoDefault(False)
        self.emergency.setDefault(False)
        self.emergency.setFlat(False)
        self.emergency.setObjectName("emergency")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_12.setText(_translate("MainWindow", "Peptide Station"))
        self.label_78.setText(_translate("MainWindow", "Status：ready"))
        self.label_79.setText(_translate("MainWindow", "TCP：connected"))
        self.label_6.setText(_translate("MainWindow", "Liquid Station"))
        self.label_22.setText(_translate("MainWindow", "Status：ready"))
        self.label_23.setText(_translate("MainWindow", "TCP：connected"))
        self.label_11.setText(_translate("MainWindow", "Reactor Station"))
        self.label_26.setText(_translate("MainWindow", "Status：ready"))
        self.label_41.setText(_translate("MainWindow", "TCP：connected"))
        self.label_3.setText(_translate("MainWindow", "Mobile Station"))
        self.label_24.setText(_translate("MainWindow", "TCP：connected"))
        self.label_25.setText(_translate("MainWindow", "Status：ready"))
        self.label_8.setText(_translate("MainWindow", "Solid Station"))
        self.label_15.setText(_translate("MainWindow", "TCP：connected"))
        self.label_21.setText(_translate("MainWindow", "Status：ready"))
        self.file.setText(_translate("MainWindow", "Task File"))
        self.label_13.setText(_translate("MainWindow", "Task File Info"))
        self.pre.setText(_translate("MainWindow", "Pre-Reaction"))
        self.post.setText(_translate("MainWindow", "Post-Reaction"))
        self.label_9.setText(_translate("MainWindow", "Experiment Selection"))
        self.stop1.setText(_translate("MainWindow", "Solid Station     "))
        self.stop2.setText(_translate("MainWindow", "Liquid Station   "))
        self.stop3.setText(_translate("MainWindow", "Mobile Station "))
        self.stop5.setText(_translate("MainWindow", "Reactor Station "))
        self.stop4.setText(_translate("MainWindow", "Peptide Station"))
        self.label_14.setText(_translate("MainWindow", "Program Execution Details"))
        self.label_10.setText(_translate("MainWindow", "Experimental Workflow"))
        self.c1.setText(_translate("MainWindow", "open cap"))
        self.c2.setText(_translate("MainWindow", "weighing"))
        self.c3.setText(_translate("MainWindow", "liquid"))
        self.c4.setText(_translate("MainWindow", "close cap"))
        self.c5.setText(_translate("MainWindow", "reaction"))
        self.c6.setText(_translate("MainWindow", "open cap"))
        self.c7.setText(_translate("MainWindow", "liquid"))
        self.c9.setText(_translate("MainWindow", "close cap"))
        self.c8.setText(_translate("MainWindow", "pre nmr"))
        self.c10.setText(_translate("MainWindow", "open cap"))
        self.c11.setText(_translate("MainWindow", "post nmr"))
        self.c12.setText(_translate("MainWindow", "close cap"))
        self.start.setText(_translate("MainWindow", "Start Task"))
        self.emergency.setText(_translate("MainWindow", "E-Stop"))
