# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tcp.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TCPSettings(object):
    def setupUi(self, TCPSettings):
        TCPSettings.setObjectName("TCPSettings")
        TCPSettings.resize(260, 142)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TCPSettings.sizePolicy().hasHeightForWidth())
        TCPSettings.setSizePolicy(sizePolicy)
        TCPSettings.setMinimumSize(QtCore.QSize(260, 142))
        TCPSettings.setMaximumSize(QtCore.QSize(260, 142))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("icon/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        TCPSettings.setWindowIcon(icon)
        TCPSettings.setStyleSheet(
            "QWidget { \n"
            "border-radius: 5px; /* Set rounded corners */ \n"
            "background-color: #ffffff; /* Set background color */ \n"
            "}"
        )
        self.frame = QtWidgets.QFrame(TCPSettings)
        self.frame.setGeometry(QtCore.QRect(0, 0, 260, 142))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.frame.setFont(font)
        self.frame.setStyleSheet(
            "QFrame#frame { \n"
            "border-radius: 5px; /* Set rounded corners */ \n"
            "background-color: #ecedee; /* Set background color */ \n"
            "}"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 260, 142))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.frame_8.setFont(font)
        self.frame_8.setStyleSheet(
            "/* QLabel Default style */\n"
            "QLabel {\n"
            "    color:  #000000; /* Text color */\n"
            "    font-size: 20px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "    qproperty-alignment: 'AlignCenter';\n"
            "}\n"
            "QFrame#frame_8 {\n"
            "    background-color: #ffffff; /* Set background color */ \n"
            "    border-radius: 5px;\n"
            "}\n"
            "QLineEdit {\n"
            "    color:  #000000; /* Text color */\n"
            "    font-size: 20px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "    qproperty-alignment: 'AlignCenter';\n"
            "    font-family: 'Microsoft YaHei'; /* Font set to Microsoft YaHei */\n"
            "    font-weight: bold; /* Set bold font */\n"
            "}\n"
            "QPushButton {\n"
            "    color:  #000000; /* Text color */\n"
            "    font-size: 20px; /* Font size */\n"
            "    border-radius: 5px; /* Rounded corners */\n"
            "    font-family: 'Microsoft YaHei'; /* Font set to Microsoft YaHei */\n"
            "    font-weight: bold; /* Set bold font */\n"
            "    border: 1px solid #000000\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "/* QPushButton Hover state */\n"
            "QPushButton:hover {\n"
            "    background-color: #ecedee; /* Dark blue background */\n"
            "    color: black; /* Hover stateWhite text */\n"
            "}\n"
            "\n"
            "/* QPushButton Pressed state */\n"
            "QPushButton:pressed {\n"
            "    background-color: #ecedee; /* Darker blue background when pressed */\n"
            "    color: black; /* Pressed stateWhite text */\n"
            "}"
        )
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_15 = QtWidgets.QLabel(self.frame_8)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 50, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(50, 32))
        self.label_15.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_15.setFont(font)
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_21 = QtWidgets.QLabel(self.frame_8)
        self.label_21.setGeometry(QtCore.QRect(10, 52, 80, 32))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(0, 0))
        self.label_21.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_21.setFont(font)
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.confirm = QtWidgets.QPushButton(self.frame_8)
        self.confirm.setGeometry(QtCore.QRect(32, 94, 86, 32))
        self.confirm.setObjectName("confirm")
        self.cancel = QtWidgets.QPushButton(self.frame_8)
        self.cancel.setGeometry(QtCore.QRect(142, 94, 86, 32))
        self.cancel.setObjectName("cancel")
        self.i1 = QtWidgets.QLineEdit(self.frame_8)
        self.i1.setGeometry(QtCore.QRect(53, 10, 40, 32))
        self.i1.setObjectName("i1")
        self.i2 = QtWidgets.QLineEdit(self.frame_8)
        self.i2.setGeometry(QtCore.QRect(103, 10, 40, 32))
        self.i2.setObjectName("i2")
        self.i3 = QtWidgets.QLineEdit(self.frame_8)
        self.i3.setGeometry(QtCore.QRect(153, 10, 40, 32))
        self.i3.setObjectName("i3")
        self.i4 = QtWidgets.QLineEdit(self.frame_8)
        self.i4.setGeometry(QtCore.QRect(203, 10, 40, 32))
        self.i4.setObjectName("i4")
        self.port = QtWidgets.QLineEdit(self.frame_8)
        self.port.setGeometry(QtCore.QRect(87, 52, 70, 32))
        self.port.setObjectName("port")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_10.setGeometry(QtCore.QRect(93, 10, 10, 32))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_11.setGeometry(QtCore.QRect(143, 10, 10, 32))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_12.setGeometry(QtCore.QRect(193, 10, 10, 32))
        self.lineEdit_12.setObjectName("lineEdit_12")

        self.retranslateUi(TCPSettings)
        QtCore.QMetaObject.connectSlotsByName(TCPSettings)

    def retranslateUi(self, TCPSettings):
        _translate = QtCore.QCoreApplication.translate
        TCPSettings.setWindowTitle(_translate("TCPSettings", "TCP Setting"))
        self.label_15.setText(_translate("TCPSettings", "IP : "))
        self.label_21.setText(_translate("TCPSettings", "PORT :"))
        self.confirm.setText(_translate("TCPSettings", "Submit"))
        self.cancel.setText(_translate("TCPSettings", "Cancel"))
        self.i1.setText(_translate("TCPSettings", "255"))
        self.i2.setText(_translate("TCPSettings", "255"))
        self.i3.setText(_translate("TCPSettings", "255"))
        self.i4.setText(_translate("TCPSettings", "255"))
        self.port.setText(_translate("TCPSettings", "65536"))
        self.lineEdit_10.setText(_translate("TCPSettings", "."))
        self.lineEdit_11.setText(_translate("TCPSettings", "."))
        self.lineEdit_12.setText(_translate("TCPSettings", "."))
